version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/app
      - ./langgraph:/langgraph