version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/app
