from pydantic import BaseModel, Field
from typing import List, Optional, Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage
from .structure_output import StudyPlanOutput

class Course(BaseModel):
    id: str = Field(..., description="Unique identifier of the course")
    name: str = Field(..., description="Name of the course")
    description: Optional[str] = Field("", description="Description of the course")
    state: Optional[str] = Field("UNKNOWN", description="State of the course, e.g., ACTIVE, ARCHIVED")

class Coursework(BaseModel):
    id: str = Field(..., description="Unique identifier of the coursework")
    title: str = Field(..., description="Title of the coursework")
    description: Optional[str] = Field("", description="Description of the coursework")
    state: Optional[str] = Field("UNKNOWN", description="State of the coursework, e.g., PUBLISHED, DRAFT")
    dueDate: Optional[dict] = Field(None, description="Due date of the coursework as a dict {year, month, day}")
    dueTime: Optional[dict] = Field(None, description="Due time of the coursework as a dict {hours, minutes}")

class CourseWorkMaterial(BaseModel):
    id: str = Field(..., description="Unique identifier of the course work material")
    title: str = Field(..., description="Title of the material")
    description: Optional[str] = Field("", description="Description of the material")
    state: Optional[str] = Field("UNKNOWN", description="State of the material, e.g., PUBLISHED, DRAFT")
    materials: List[dict] = Field(default_factory=list, description="List of attached materials (Drive files, links, etc.)")
    creationTime: Optional[str] = Field(None, description="Creation timestamp")
    updateTime: Optional[str] = Field(None, description="Last update timestamp")

class StudentInteraction(BaseModel):
    current_course: Optional[Course] = Field(None, description="The course currently being interacted with")
    current_coursework: Optional[Coursework] = Field(None, description="The coursework currently being discussed")
    student_question: Optional[str] = Field("", description="The last question or query from the student")
    ai_response: Optional[str] = Field("", description="The latest response generated by the AI")
    recommendations: List[str] = Field(default_factory=list, description="Study tips, resources, or guidance suggested by the AI")
    observation: Optional[str] = Field("", description="What the agent observed from its action")

class GraphState(TypedDict):
    courses: List[Course]  
    courseworks: List[Coursework]
    materials: List[CourseWorkMaterial]
    current_interaction: StudentInteraction 
    agent_messages: Annotated[list, add_messages]  
    requested_course_id: Optional[str]
    sendable: bool 
    trials: int
    max_trials: int
    rewrite_feedback: str
    student_id: Optional[str]
    student_context: Optional[str]
    conversation_history: List[BaseMessage]
    query_category: Optional[str]
    is_first_message: Optional[bool]
    study_plan: Optional[StudyPlanOutput]
