package data

import (
	"database/sql"
	"fmt"
	"os"
)

var db *sql.DB

func InitDB() error {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		return fmt.Errorf("DATABASE_URL not set in environment")
	}

	var err error
	db, err = sql.Open("postgres", dbURL)
	if err != nil {
		return fmt.Errorf("error opening database: %w", err)
	}

	err = db.Ping()
	if err != nil {
		return fmt.Errorf("error connecting to the database: %w", err)
	}

	fmt.Println("Successfully connected to the database via direct connection")

	err = Migrate()
	if err != nil {
		return fmt.Errorf("migration failed: %w", err)
	}

	return nil
}

func Migrate() error {
	queries := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			email TEXT UNIQUE NOT NULL,
			password TEXT NOT NULL,
			role_id INT DEFAULT 1,
			created_at TIMESTAMPTZ DEFAULT NOW()
		);`,
		`CREATE TABLE IF NOT EXISTS user_memo (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT REFERENCES users(id),
			user_query TEXT,
			ai_query TEXT,
			category TEXT,
			emotion TEXT,
			created_at TIMESTAMPTZ DEFAULT NOW()
		);`,
		`CREATE TABLE IF NOT EXISTS preferences (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT REFERENCES users(id),
			language VARCHAR DEFAULT '',
			tone VARCHAR DEFAULT '',
			name VARCHAR DEFAULT '',
			preference TEXT DEFAULT '',
			created_at TIMESTAMPTZ DEFAULT NOW()
		);`,
	}

	for _, q := range queries {
		_, err := db.Exec(q)
		if err != nil {
			return fmt.Errorf("error executing query [%s]: %w", q, err)
		}
	}

	fmt.Println("Database migrations completed successfully")
	return nil
}
