from pydantic import BaseModel, Field 
from typing import Any, List, Optional, Annotated
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from datetime import datetime

class Event(BaseModel):
    id: str = Field (..., description="Unique identifier of the event")
    summary: str = Field(..., description="summary of the event")
    start_datetime: datetime = Field(..., description="start datetime of the event")
    end_datetime: Optional[datetime] = Field(..., description="end datetime of the event")
    timezone: Optional[str] = Field(..., description="the timezone")
    location: Optional[str] = Field(..., description="the location")
    description : Optional[str] = Field(..., description="a description of the event")
    reminders: Optional[dict] = Field(..., description="the remainder")
    coference_data:Optional[bool] = Field (..., description="the conference data")
    color_id: Optional[int] = Field (..., description="the color of the event")

class UserInteraction(BaseModel):
    user_request:str = Field("", description= "The last query of the user")
    ai_response : str = Field("", description= "The latest response generated by the ai")
    recommendations: List[str] = Field(default_factory=list, description="time managemenr tips or guidance suggested by the AI")
    observation: Optional[str] = Field("", description="What the agent observed from its action")

class GraphState(TypedDict):
    events: List[Event]
    current_interaction: UserInteraction
    agent_messages: Annotated[list, add_messages]
    sendable:bool
    trials:int
    max_trials:int 
    rewrite_feedback:str
    user_context: Optional[str]
    conversation_history: List[BaseMessage]
    query_category: Optional[str]
    route: Optional[str]
    calendar_result: Optional[Any]
    is_first_message: Optional[bool]
    student_id: Optional[str]
