FROM python:3.9-slim

WORKDIR /app

RUN apt-get update --fix-missing \
    && apt-get install -y --no-install-recommends \
       gcc \
       build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

RUN apt-get purge -y --auto-remove gcc build-essential

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
